# Generated by Django 4.0.5 on 2022-12-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleep',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
