# Generated by Django 4.0.5 on 2022-12-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_food_meal_sleep_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medication',
            field=models.BooleanField(default=0),
        ),
    ]
