# Generated by Django 4.0.5 on 2022-12-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_profile_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taken',
            old_name='when',
            new_name='date',
        ),
    ]
