# Generated by Django 4.0.5 on 2023-01-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0004_rename_when_taken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(),
        ),
    ]
