# Generated by Django 4.0.5 on 2022-11-12 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_healthlog', '0002_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('calories', models.CharField(default=0, max_length=255)),
                ('date', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePerson', to=settings.AUTH_USER_MODEL)),
                ('theDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toTheLog', to='core_healthlog.log')),
            ],
        ),
    ]
