# Generated by Django 4.0.5 on 2022-11-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_healthlog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
