from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(Profile)
admin.site.register(SymptomList)
admin.site.register(Medication)
admin.site.register(Week)
admin.site.register(Day)
admin.site.register(Feeling)
admin.site.register(Symptom)
admin.site.register(Taken)
admin.site.register(Sugar)
admin.site.register(Food)
admin.site.register(Sleep)
admin.site.register(Tracker)
admin.site.register(Provider)
admin.site.register(Comment)
admin.site.register(Reply)
admin.site.register(Note)